<?php
/**
 * Created by PhpStorm.
 * User: jiangwei
 * Date: 2020/1/6
 * Time: 14:05
 */

class Simulate3d_model extends POP_Model
{
    public function saveApplyTrial($data)
    {
        return parent::executeSave('pop136.t_leave_message', $data); // TODO: Change the autogenerated stub
    }
}